### ISSUE TITLE
Model Societal impacts

### ISSUE THREAD

**Issue by Dobios** [Dobios/SURE_WP3#4]
The goal is to model the impact certain decisions have on the people. This is done by managing the modelling metrics:  
  - __Salary range__: a fixed unit that shows the overall wealth your population has  
  - __Energy stability__: Models the frequency at which the population's energy demand is met.  
  - __Energy Affordability__: Models how affordable the current energy is. This becomes lower if there is a higher availability than demand.  

All of these metrics are then put together into an overall "support" amount.

**Comment by astonedf** [comment]
Instead of the modelling metrics, I imagine more like scenarios (easy, normal, hard) which sort of represent different political views (left, center, right) and which would impact the chance (%) to implement new policies. So each policy would have a set % depending on the chosen scenario and then that % would also be influenced by the support bar (i.e. over 50% would boost the chances)
The player's support will be affected by the way they play, how they react to shocks, if they build too many wind/solar upgrades or if they provide more than enough energy
